<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="attributesTest" nsURI="testmodel" nsPrefix="testmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="996"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigIntegerDefValWrong"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="996"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytePrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        defaultValueLiteral="66"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteArrayDefVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"
        defaultValueLiteral="68656c6c6f20656d66"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ECharacterObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charObjDefVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ECharacterObject"
        defaultValueLiteral="w"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doublePrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="9.9f"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="666"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eList" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateDefVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2005-01-29'T'20:25:30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listString" lowerBound="2"
        upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listInt" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listShort" upperBound="5"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listInt1DefVal" ordered="false"
        lowerBound="3" upperBound="6" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-99"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="map" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
